sonar.projectKey=asx-stock-predictor
sonar.projectName=ASX Stock Price Predictor
sonar.projectVersion=1.0
sonar.sources=app
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11
sonar.exclusions=**/migrations/**,**/__pycache__/**